"""Infrastructure-as-Code exporters — turn an LZDesign into deployable artifacts.

Three formats:
  * Terraform (AWS Organizations + OUs + accounts + SCPs)
  * Landing Zone Accelerator (LZA) organization-config.yaml
  * Control Tower setup checklist + Account Factory inputs (Markdown)

Generation is deterministic (no LLM) so output is reviewable and stable.
"""

import io
import json
import re
import zipfile

from lz_core import LZDesign, workload_account_count

# ---------------------------------------------------------------------------
# Real SCP policy documents for the core guardrails
# ---------------------------------------------------------------------------

_SCP_DOCS = {
    "deny_leave_org": {
        "Version": "2012-10-17",
        "Statement": [{"Sid": "DenyLeaveOrg", "Effect": "Deny",
                       "Action": "organizations:LeaveOrganization", "Resource": "*"}],
    },
    "deny_root_user": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyRootUser", "Effect": "Deny", "Action": "*", "Resource": "*",
            "Condition": {"StringLike": {"aws:PrincipalArn": "arn:aws:iam::*:root"}},
        }],
    },
    "region_restriction": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyOutsideApprovedRegions", "Effect": "Deny",
            "NotAction": [
                "iam:*", "organizations:*", "route53:*", "cloudfront:*",
                "waf:*", "wafv2:*", "support:*", "budgets:*", "sts:*",
            ],
            "Resource": "*",
            "Condition": {"StringNotEquals": {"aws:RequestedRegion": "__REGIONS__"}},
        }],
    },
    "protect_security_services": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenySecurityTampering", "Effect": "Deny",
            "Action": [
                "cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:UpdateTrail",
                "config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder",
                "config:DeleteDeliveryChannel",
                "guardduty:DeleteDetector", "guardduty:DisassociateFromMasterAccount",
                "securityhub:DisableSecurityHub",
            ],
            "Resource": "*",
        }],
    },
    "deny_imdsv1": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "RequireImdsV2", "Effect": "Deny", "Action": "ec2:RunInstances",
            "Resource": "arn:aws:ec2:*:*:instance/*",
            "Condition": {"StringNotEquals": {"ec2:MetadataHttpTokens": "required"}},
        }],
    },
}


def _hcl_jsonencode(doc: dict, regions: list) -> str:
    s = json.dumps(doc, indent=2)
    if "__REGIONS__" in s:
        s = s.replace('"__REGIONS__"', json.dumps(regions))
    return s


# ---------------------------------------------------------------------------
# Terraform
# ---------------------------------------------------------------------------

def terraform_export(d: LZDesign) -> str:
    n_env = [e for e in d.environments]
    workloads = [f"workload-{i + 1}" for i in range(d.num_workloads)]
    per_env = d.account_strategy == "Account per workload per environment"
    per_wl = d.account_strategy in ("Account per workload", "Account per workload per environment")

    out = []
    out.append(f'''# ---------------------------------------------------------------
# AWS Landing Zone — generated by AWS Landing Zone Studio
# Strategy: {d.account_strategy} | Network: {d.network_pattern}
# Review carefully before applying. Account emails MUST be unique.
# ---------------------------------------------------------------

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{ source = "hashicorp/aws", version = ">= 5.40" }}
  }}
}}

provider "aws" {{
  region = "{d.regions[0] if d.regions else 'us-east-1'}"
  # Run from the management account (or a delegated admin for Organizations)
}}

variable "account_email_domain" {{
  description = "Domain used for root emails, e.g. aws+%s@example.com"
  type        = string
}}

locals {{
  environments = {json.dumps(n_env)}
  workloads    = {json.dumps(workloads)}
  approved_regions = {json.dumps(d.regions)}
}}

# ----------------------------- Organization -----------------------------

resource "aws_organizations_organization" "this" {{
  feature_set = "ALL"
  enabled_policy_types = ["SERVICE_CONTROL_POLICY", "TAG_POLICY"]
  aws_service_access_principals = [
    "cloudtrail.amazonaws.com",
    "config.amazonaws.com",
    "guardduty.amazonaws.com",
    "securityhub.amazonaws.com",
    "sso.amazonaws.com",
    "backup.amazonaws.com",
  ]
}}

# ----------------------------- OU structure -----------------------------

resource "aws_organizations_organizational_unit" "security" {{
  name      = "Security"
  parent_id = aws_organizations_organization.this.roots[0].id
}}

resource "aws_organizations_organizational_unit" "infrastructure" {{
  name      = "Infrastructure"
  parent_id = aws_organizations_organization.this.roots[0].id
}}

resource "aws_organizations_organizational_unit" "workloads" {{
  name      = "Workloads"
  parent_id = aws_organizations_organization.this.roots[0].id
}}
''')

    if per_env:
        out.append('''
resource "aws_organizations_organizational_unit" "workloads_prod" {
  name      = "Prod"
  parent_id = aws_organizations_organizational_unit.workloads.id
}

resource "aws_organizations_organizational_unit" "workloads_nonprod" {
  name      = "NonProd"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
''')

    out.append('''
resource "aws_organizations_organizational_unit" "sandbox" {
  name      = "Sandbox"
  parent_id = aws_organizations_organization.this.roots[0].id
}

resource "aws_organizations_organizational_unit" "suspended" {
  name      = "Suspended"
  parent_id = aws_organizations_organization.this.roots[0].id
}

# ----------------------------- Core accounts -----------------------------

resource "aws_organizations_account" "log_archive" {
  name      = "log-archive"
  email     = format(var.account_email_domain, "log-archive")
  parent_id = aws_organizations_organizational_unit.security.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}

resource "aws_organizations_account" "security_tooling" {
  name      = "security-tooling"
  email     = format(var.account_email_domain, "security-tooling")
  parent_id = aws_organizations_organizational_unit.security.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}
''')

    if d.network_pattern != "Flat VPC peering":
        out.append('''
resource "aws_organizations_account" "network" {
  name      = "network"
  email     = format(var.account_email_domain, "network")
  parent_id = aws_organizations_organizational_unit.infrastructure.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}
''')

    out.append('''
resource "aws_organizations_account" "shared_services" {
  name      = "shared-services"
  email     = format(var.account_email_domain, "shared-services")
  parent_id = aws_organizations_organizational_unit.infrastructure.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}

# ---------------------------- Workload accounts ----------------------------
''')

    if per_env:
        out.append('''
locals {
  workload_accounts = {
    for pair in setproduct(local.workloads, local.environments) :
    "${pair[0]}-${pair[1]}" => {
      workload = pair[0]
      env      = pair[1]
      prod     = pair[1] == "prod"
    }
  }
}

resource "aws_organizations_account" "workload" {
  for_each  = local.workload_accounts
  name      = each.key
  email     = format(var.account_email_domain, each.key)
  parent_id = each.value.prod ? aws_organizations_organizational_unit.workloads_prod.id : aws_organizations_organizational_unit.workloads_nonprod.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
}
''')
    elif per_wl:
        out.append('''
resource "aws_organizations_account" "workload" {
  for_each  = toset(local.workloads)
  name      = each.key
  email     = format(var.account_email_domain, each.key)
  parent_id = aws_organizations_organizational_unit.workloads.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
}
''')
    elif d.account_strategy == "Account per environment":
        out.append('''
resource "aws_organizations_account" "workload" {
  for_each  = toset(local.environments)
  name      = "workloads-${each.key}"
  email     = format(var.account_email_domain, "workloads-${each.key}")
  parent_id = aws_organizations_organizational_unit.workloads.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
}
''')

    # SCPs
    out.append("\n# ------------------------- Service Control Policies -------------------------\n")
    scp_targets = {
        "deny_leave_org": "aws_organizations_organization.this.roots[0].id",
        "deny_root_user": "aws_organizations_organizational_unit.workloads.id",
        "region_restriction": "aws_organizations_organization.this.roots[0].id",
        "protect_security_services": "aws_organizations_organization.this.roots[0].id",
        "deny_imdsv1": "aws_organizations_organizational_unit.workloads.id",
    }
    for name, doc in _SCP_DOCS.items():
        out.append(f'''
resource "aws_organizations_policy" "{name}" {{
  name    = "{name.replace('_', '-')}"
  type    = "SERVICE_CONTROL_POLICY"
  content = jsonencode({_hcl_jsonencode(doc, d.regions)})
}}

resource "aws_organizations_policy_attachment" "{name}" {{
  policy_id = aws_organizations_policy.{name}.id
  target_id = {scp_targets[name]}
}}
''')

    out.append('''
# Suspended OU: deny everything
resource "aws_organizations_policy" "suspended_deny_all" {
  name = "suspended-deny-all"
  type = "SERVICE_CONTROL_POLICY"
  content = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Sid = "DenyAll", Effect = "Deny", Action = "*", Resource = "*" }]
  })
}

resource "aws_organizations_policy_attachment" "suspended_deny_all" {
  policy_id = aws_organizations_policy.suspended_deny_all.id
  target_id = aws_organizations_organizational_unit.suspended.id
}
''')
    return "".join(out)


# ---------------------------------------------------------------------------
# Landing Zone Accelerator config
# ---------------------------------------------------------------------------

def lza_config(d: LZDesign) -> str:
    per_env = d.account_strategy == "Account per workload per environment"
    envs = d.environments
    home = d.regions[0] if d.regions else "us-east-1"

    lines = [f"""# organization-config.yaml — Landing Zone Accelerator
# Generated by AWS Landing Zone Studio. Review before deploying with LZA.
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Workloads"""]
    if per_env:
        lines.append("""  - name: Workloads/Prod
  - name: Workloads/NonProd""")
    lines.append("""  - name: Sandbox
  - name: Suspended

serviceControlPolicies:
  - name: deny-leave-org
    description: Prevent accounts from leaving the organization
    policy: scp-deny-leave-org.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Root]
  - name: region-restriction
    description: Deny activity outside approved regions
    policy: scp-region-restriction.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Root]
  - name: protect-security-services
    description: Deny tampering with CloudTrail / Config / GuardDuty / Security Hub
    policy: scp-protect-security.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Root]
  - name: suspended-deny-all
    description: Quarantine policy
    policy: scp-deny-all.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Suspended]

taggingPolicies: []
backupPolicies: []""")

    lines.append(f"""

# accounts-config.yaml (fragment)
mandatoryAccounts:
  - name: Management
    description: Organization management account
    email: aws+management@example.com   # CHANGE ME
    organizationalUnit: Root
  - name: LogArchive
    description: Immutable centralized logs
    email: aws+log-archive@example.com  # CHANGE ME
    organizationalUnit: Security
  - name: Audit
    description: Security tooling / delegated admin
    email: aws+audit@example.com        # CHANGE ME
    organizationalUnit: Security

workloadAccounts:""")
    if per_env:
        for i in range(min(d.num_workloads, 50)):
            for e in envs:
                ou = "Workloads/Prod" if e == "prod" else "Workloads/NonProd"
                lines.append(f"""  - name: workload-{i + 1}-{e}
    email: aws+workload-{i + 1}-{e}@example.com  # CHANGE ME
    organizationalUnit: {ou}""")
    else:
        for i in range(min(d.num_workloads, 50)):
            lines.append(f"""  - name: workload-{i + 1}
    email: aws+workload-{i + 1}@example.com  # CHANGE ME
    organizationalUnit: Workloads""")

    lines.append(f"""

# global-config.yaml (fragment)
homeRegion: {home}
enabledRegions: {json.dumps(d.regions)}
managementAccountAccessRole: OrganizationAccountAccessRole
cloudwatchLogRetentionInDays: 365
centralizedLoggingBucket:
  lifecycleRules:
    - enabled: true
      expiration: 730
""")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Control Tower checklist
# ---------------------------------------------------------------------------

def control_tower_checklist(d: LZDesign) -> str:
    per_env = d.account_strategy == "Account per workload per environment"
    home = d.regions[0] if d.regions else "us-east-1"
    md = [f"""# Control Tower Setup — {d.org_size} profile

## 1. Prerequisites
- [ ] Management account with billing + root access secured (MFA, no access keys)
- [ ] Two fresh email addresses for **Log Archive** and **Audit** accounts
- [ ] Home region: **{home}** (governed regions: {', '.join(d.regions)})

## 2. Launch Control Tower
- [ ] Console -> Control Tower -> Set up landing zone
- [ ] Foundational OU: `Security` (Log Archive + Audit created automatically)
- [ ] Additional OU: `Workloads`{' with `Prod` / `NonProd` children' if per_env else ''}
- [ ] Enable AWS CloudTrail org trail (mandatory control)
- [ ] KMS encryption for Control Tower resources: **enabled**

## 3. Post-launch configuration
- [ ] Create OUs: `Infrastructure`, `Sandbox`, `Suspended` (register each with CT)
- [ ] Enable IAM Identity Center; connect {"external IdP (" + d.identity_model + ")" if d.identity_model.startswith("External") else "Identity Center directory"}
- [ ] Delegate GuardDuty + Security Hub + Config admin to the **Audit** account
- [ ] Apply elective/proactive controls per compliance: {', '.join(d.compliance) or 'baseline only'}

## 4. Account Factory
Provision accounts with these inputs:

| Account | OU | Purpose |
|---|---|---|
| network | Infrastructure | {d.network_pattern} hub |
| shared-services | Infrastructure | CI/CD, AMIs, registries |"""]
    if per_env:
        md.append("".join(
            f"\n| workload-{i + 1}-{e} | Workloads/{'Prod' if e == 'prod' else 'NonProd'} | Workload account |"
            for i in range(min(d.num_workloads, 20)) for e in d.environments))
    else:
        md.append("".join(
            f"\n| workload-{i + 1} | Workloads | Workload account |"
            for i in range(min(d.num_workloads, 20))))

    md.append(f"""

## 5. Network ({d.network_pattern})
- [ ] Provision Transit Gateway / core network in the **network** account
- [ ] Share via AWS RAM with the Workloads OU
- [ ] {"Centralize egress (NAT + inspection) in the network account" if "egress" in d.network_pattern.lower() else "Plan egress per the chosen pattern"}

## 6. Operations
- [ ] Account Factory Customization (AFT) or Customizations for Control Tower (CfCT) for baselines-as-code
- [ ] Budgets + budget actions on Sandbox OU
- [ ] {"AWS Backup org policies with cross-region copies" if d.backup_dr else "Define backup strategy per workload"}
""")
    return "".join(md)


# ---------------------------------------------------------------------------
# Replication bundle — replicate the blueprint across N organizations
# ---------------------------------------------------------------------------

def _blueprint_module(d: LZDesign) -> str:
    """The landing-zone blueprint as a reusable Terraform module (no provider /
    terraform block — those are supplied by each per-org root)."""
    per_env = d.account_strategy == "Account per workload per environment"
    per_wl = d.account_strategy in ("Account per workload", "Account per workload per environment")
    out = ['''# modules/landing-zone/main.tf
# Reusable landing-zone blueprint, instantiated once per target organization by
# the roots under orgs/<name>/. The provider is supplied by each root module.

resource "aws_organizations_organization" "this" {
  feature_set          = "ALL"
  enabled_policy_types = ["SERVICE_CONTROL_POLICY", "TAG_POLICY"]
  aws_service_access_principals = [
    "cloudtrail.amazonaws.com", "config.amazonaws.com", "guardduty.amazonaws.com",
    "securityhub.amazonaws.com", "sso.amazonaws.com", "backup.amazonaws.com",
  ]
}

resource "aws_organizations_organizational_unit" "security" {
  name = "Security"
  parent_id = aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "infrastructure" {
  name = "Infrastructure"
  parent_id = aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "workloads" {
  name = "Workloads"
  parent_id = aws_organizations_organization.this.roots[0].id
}
''']
    if per_env:
        out.append('''resource "aws_organizations_organizational_unit" "workloads_prod" {
  name = "Prod"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
resource "aws_organizations_organizational_unit" "workloads_nonprod" {
  name = "NonProd"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
''')
    out.append('''resource "aws_organizations_organizational_unit" "sandbox" {
  name = "Sandbox"
  parent_id = aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "suspended" {
  name = "Suspended"
  parent_id = aws_organizations_organization.this.roots[0].id
}

resource "aws_organizations_account" "log_archive" {
  name = "log-archive"
  email = format(var.account_email_domain, "log-archive")
  parent_id = aws_organizations_organizational_unit.security.id
  lifecycle { prevent_destroy = true }
}
resource "aws_organizations_account" "audit" {
  name = "audit"
  email = format(var.account_email_domain, "audit")
  parent_id = aws_organizations_organizational_unit.security.id
  lifecycle { prevent_destroy = true }
}
resource "aws_organizations_account" "shared_services" {
  name = "shared-services"
  email = format(var.account_email_domain, "shared-services")
  parent_id = aws_organizations_organizational_unit.infrastructure.id
}
''')
    if d.network_pattern != "Flat VPC peering":
        out.append('''resource "aws_organizations_account" "network" {
  name = "network"
  email = format(var.account_email_domain, "network")
  parent_id = aws_organizations_organizational_unit.infrastructure.id
}
''')
    if per_env:
        out.append('''
locals {
  workload_accounts = {
    for pair in setproduct(var.workloads, var.environments) :
    "${pair[0]}-${pair[1]}" => { prod = pair[1] == "prod" }
  }
}
resource "aws_organizations_account" "workload" {
  for_each = local.workload_accounts
  name = each.key
  email = format(var.account_email_domain, each.key)
  parent_id = each.value.prod ? aws_organizations_organizational_unit.workloads_prod.id : aws_organizations_organizational_unit.workloads_nonprod.id
}
''')
    elif per_wl:
        out.append('''
resource "aws_organizations_account" "workload" {
  for_each = toset(var.workloads)
  name = each.key
  email = format(var.account_email_domain, each.key)
  parent_id = aws_organizations_organizational_unit.workloads.id
}
''')
    else:
        out.append('''
resource "aws_organizations_account" "workload" {
  for_each = toset(var.environments)
  name = "workloads-${each.key}"
  email = format(var.account_email_domain, "workloads-${each.key}")
  parent_id = aws_organizations_organizational_unit.workloads.id
}
''')
    out.append("\n# ------------------------- Service Control Policies -------------------------\n")
    scp_targets = {
        "deny_leave_org": "aws_organizations_organization.this.roots[0].id",
        "deny_root_user": "aws_organizations_organizational_unit.workloads.id",
        "region_restriction": "aws_organizations_organization.this.roots[0].id",
        "protect_security_services": "aws_organizations_organization.this.roots[0].id",
        "deny_imdsv1": "aws_organizations_organizational_unit.workloads.id",
    }
    for name, doc in _SCP_DOCS.items():
        out.append(f'''
resource "aws_organizations_policy" "{name}" {{
  name = "{name.replace('_', '-')}"
  type = "SERVICE_CONTROL_POLICY"
  content = jsonencode({_hcl_jsonencode(doc, d.regions)})
}}
resource "aws_organizations_policy_attachment" "{name}" {{
  policy_id = aws_organizations_policy.{name}.id
  target_id = {scp_targets[name]}
}}
''')
    return "".join(out)


def _blueprint_variables(d: LZDesign) -> str:
    return f'''# modules/landing-zone/variables.tf
variable "account_email_domain" {{
  description = "printf-style email pattern, e.g. aws+%s@org.example.com"
  type        = string
}}
variable "regions" {{
  type    = list(string)
  default = {json.dumps(d.regions)}
}}
variable "workloads" {{
  type    = list(string)
  default = {json.dumps([f"workload-{i + 1}" for i in range(d.num_workloads)])}
}}
variable "environments" {{
  type    = list(string)
  default = {json.dumps(d.environments)}
}}
'''


def _org_root(d: LZDesign, org_name: str) -> str:
    home = d.regions[0] if d.regions else "us-east-1"
    return f'''# orgs/{org_name}/main.tf
# One Terraform root per target organization. Configure the provider to operate
# in THIS org's management account, then call the shared blueprint module. Each
# org is a SEPARATE Terraform state.

terraform {{
  required_version = ">= 1.5"
  required_providers {{ aws = {{ source = "hashicorp/aws", version = ">= 5.40" }} }}
  # backend "s3" {{ bucket = "tfstate-{org_name}" key = "landing-zone.tfstate" region = "{home}" }}
}}

provider "aws" {{
  region = "{home}"
  # Run from / assume into the {org_name} management account:
  # assume_role {{ role_arn = "arn:aws:iam::<{org_name}_MGMT_ACCOUNT_ID>:role/OrganizationAccountAccessRole" }}
}}

module "landing_zone" {{
  source               = "../../modules/landing-zone"
  account_email_domain = "aws+%s@{org_name}.example.com"   # CHANGE ME (unique per org)
  regions              = {json.dumps(d.regions)}
  environments         = {json.dumps(d.environments)}
}}

# NOTE: GuardDuty / Security Hub / Config delegated administration is configured
# PER ORGANIZATION. Cross-org connectivity uses TGW peering / Cloud WAN /
# PrivateLink, not AWS RAM.
'''


def _aft_account_requests(d: LZDesign, org_name: str) -> str:
    per_env = d.account_strategy == "Account per workload per environment"
    rows = []
    n = min(d.num_workloads, 50)
    envs = d.environments if per_env else [None]
    for i in range(n):
        for e in envs:
            nm = f"workload-{i + 1}" + (f"-{e}" if e else "")
            ou = ("Workloads/Prod" if e == "prod" else "Workloads/NonProd") if per_env else "Workloads"
            rows.append(f'''module "{nm.replace('-', '_')}" {{
  source = "./modules/aft-account-request"
  control_tower_parameters = {{
    AccountEmail              = "aws+{nm}@{org_name}.example.com"
    AccountName               = "{nm}"
    ManagedOrganizationalUnit = "{ou}"
    SSOUserEmail              = "platform@{org_name}.example.com"
    SSOUserFirstName          = "Platform"
    SSOUserLastName           = "Team"
  }}
  account_tags = {{ "blueprint" = "{d.account_strategy}", "org" = "{org_name}" }}
}}''')
    return ("# aft/account-requests.tf — scaled workload vending via AWS Control Tower\n"
            "# Account Factory for Terraform (AFT). Commit to your AFT account-request repo;\n"
            "# AFT provisions + customizes each account through its GitOps pipeline.\n\n"
            + "\n\n".join(rows) + "\n")


def replication_bundle(d: LZDesign, org_names: list) -> bytes:
    """Build a downloadable .zip scaffold to replicate the blueprint across orgs."""
    org_names = [n for n in (org_names or []) if n] or ["org-1"]
    readme = f"""# Landing Zone replication scaffold

Generated by AWS Landing Zone Studio. Replicates the blueprint
(**{d.account_strategy}**, network **{d.network_pattern}**, governance
**{d.governance}**) across **{len(org_names)} organization(s)**: {', '.join(org_names)}.

## Pattern
Each target organization is a **separate** AWS Organization with its own
management account and Terraform state. The shared blueprint lives in
`modules/landing-zone/`; one root per org under `orgs/<name>/` configures a
provider for that org's management account and calls the module.

```
.
├── modules/landing-zone/   # reusable blueprint (OUs, SCPs, core accounts, workload vending)
├── orgs/<org>/             # one root per target org (provider + module call)
└── aft/                    # optional: scaled workload vending via Control Tower AFT
```

## Apply (per org)
```bash
cd orgs/{org_names[0]}
terraform init
terraform plan      # review — account emails MUST be unique across ALL orgs
terraform apply     # run from / assume into that org's management account
```

## Important
- **Root email uniqueness** across every account in every org.
- **Security tooling** (GuardDuty/Security Hub/Config) delegated admin is
  **per-organization** — configure it in each org's audit account.
- **Cross-org connectivity** uses TGW peering / Cloud WAN / PrivateLink (AWS RAM
  does not cross org boundaries).
- For large fleets, prefer **AFT** (`aft/`) over inline `for_each` vending.
- Reviewable starting point, not a turnkey deployment — always review before apply.
"""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.md", readme)
        z.writestr("modules/landing-zone/main.tf", _blueprint_module(d))
        z.writestr("modules/landing-zone/variables.tf", _blueprint_variables(d))
        for name in org_names:
            z.writestr(f"orgs/{name}/main.tf", _org_root(d, name))
        z.writestr(f"aft/account-requests.{org_names[0]}.tf", _aft_account_requests(d, org_names[0]))
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Hybrid connectivity — Direct Connect (+ SD-WAN) to a TGW / Cloud WAN hub
# ---------------------------------------------------------------------------

def connectivity_terraform(hub: str = "Transit Gateway", dx_speed: str = "1 Gbps",
                           redundant: bool = True, sdwan: bool = True,
                           n_spokes: int = 3) -> str:
    """Reviewable Terraform scaffold for Phase-0 hybrid connectivity. The physical
    Direct Connect connection/LAG is ordered out-of-band and referenced by ID via
    a variable. Deploy from the Network account."""
    use_cloudwan = hub == "AWS Cloud WAN"
    parts = []
    parts.append(f'''# connectivity.tf — Hybrid connectivity scaffold
# Generated by AWS Landing Zone Studio. Deploy from the **Network account**.
# Hub: {hub} | Direct Connect: {dx_speed}{' (redundant)' if redundant else ''}{' | SD-WAN overlay' if sdwan else ''}
#
# IMPORTANT: the physical Direct Connect connection/LAG is provisioned out-of-band
# (AWS console / partner). Reference its ID(s) via the variables below. Review and
# adapt VLANs, ASNs, CIDRs, and SD-WAN AMIs before applying.

terraform {{
  required_version = ">= 1.5"
  required_providers {{ aws = {{ source = "hashicorp/aws", version = ">= 5.40" }} }}
}}

provider "aws" {{ region = var.region }}

# ------------------------------- Variables -------------------------------
variable "region"             {{ type = string, default = "us-east-1" }}
variable "amazon_side_asn"    {{ type = number, default = 64512 }}
variable "customer_asn"       {{ type = number, default = 65000 }}
variable "on_prem_cidrs"      {{ type = list(string), default = ["10.100.0.0/16"] }}
variable "dx_connection_id"   {{ type = string, default = "dxcon-CHANGEME" }}   # primary DX connection
variable "dx_vlan"            {{ type = number, default = 100 }}'''
        + ('''
variable "dx_connection_id_secondary" { type = string, default = "dxcon-CHANGEME-2" }  # redundant DX
variable "dx_vlan_secondary"          { type = number, default = 101 }''' if redundant else '')
        + '''
variable "spoke_vpc_attachments" {
  description = "Workload VPC spokes to attach to the hub"
  type = map(object({ vpc_id = string, subnet_ids = list(string) }))
  default = {}
}''')

    if sdwan:
        parts.append('''variable "transit_vpc_subnet_ids" { type = list(string), default = [] }   # for SD-WAN appliances
variable "sdwan_ami"           { type = string, default = "ami-CHANGEME" }    # third-party SD-WAN AMI
variable "sdwan_instance_type" { type = string, default = "c5.large" }
variable "sdwan_peer_inside_cidr" { type = string, default = "169.254.6.0/29" }''')

    if not use_cloudwan:
        parts.append('''
# ----------------------------- Transit Gateway -----------------------------
resource "aws_ec2_transit_gateway" "hub" {
  description                     = "Landing zone hybrid hub"
  amazon_side_asn                 = var.amazon_side_asn
  auto_accept_shared_attachments  = "enable"
  default_route_table_association = "enable"
  default_route_table_propagation = "enable"
  tags = { Name = "lz-hub-tgw" }
}

# ----------------------- Direct Connect to the hub -----------------------
resource "aws_dx_gateway" "this" {
  name            = "lz-dx-gateway"
  amazon_side_asn = var.amazon_side_asn
}

resource "aws_dx_gateway_association" "tgw" {
  dx_gateway_id         = aws_dx_gateway.this.id
  associated_gateway_id = aws_ec2_transit_gateway.hub.id
  allowed_prefixes      = var.on_prem_cidrs
}

resource "aws_dx_transit_virtual_interface" "primary" {
  connection_id    = var.dx_connection_id
  dx_gateway_id    = aws_dx_gateway.this.id
  name             = "lz-transit-vif"
  vlan             = var.dx_vlan
  address_family   = "ipv4"
  bgp_asn          = var.customer_asn
}''')
        if redundant:
            parts.append('''
resource "aws_dx_transit_virtual_interface" "secondary" {
  connection_id    = var.dx_connection_id_secondary
  dx_gateway_id    = aws_dx_gateway.this.id
  name             = "lz-transit-vif-2"
  vlan             = var.dx_vlan_secondary
  address_family   = "ipv4"
  bgp_asn          = var.customer_asn
}''')
        parts.append('''
# ----------------------- Site-to-Site VPN (backup path) -----------------------
resource "aws_customer_gateway" "onprem" {
  bgp_asn    = var.customer_asn
  ip_address = "203.0.113.1"   # CHANGE ME: on-prem / SD-WAN public IP
  type       = "ipsec.1"
  tags       = { Name = "lz-onprem-cgw" }
}

resource "aws_vpn_connection" "backup" {
  customer_gateway_id = aws_customer_gateway.onprem.id
  transit_gateway_id  = aws_ec2_transit_gateway.hub.id
  type                = "ipsec.1"
  tags                = { Name = "lz-dx-backup-vpn" }
}

# ----------------------------- VPC spoke attachments -----------------------------
resource "aws_ec2_transit_gateway_vpc_attachment" "spoke" {
  for_each           = var.spoke_vpc_attachments
  transit_gateway_id = aws_ec2_transit_gateway.hub.id
  vpc_id             = each.value.vpc_id
  subnet_ids         = each.value.subnet_ids
  tags               = { Name = "lz-spoke-${each.key}" }
}''')
        if sdwan:
            parts.append('''
# --------------------- SD-WAN overlay via Transit Gateway Connect ---------------------
# Two SD-WAN appliances (HA) in the transit VPC; integrate with TGW using a
# Connect attachment (GRE + BGP). Requires a third-party SD-WAN AMI + license.
resource "aws_instance" "sdwan" {
  count                  = 2
  ami                    = var.sdwan_ami
  instance_type          = var.sdwan_instance_type
  subnet_id              = element(var.transit_vpc_subnet_ids, count.index)
  source_dest_check      = false
  tags                   = { Name = "lz-sdwan-${count.index + 1}" }
}

# Connect attachment rides on top of a VPC (or DX) TGW attachment as transport.
resource "aws_ec2_transit_gateway_connect" "sdwan" {
  transport_attachment_id = values(aws_ec2_transit_gateway_vpc_attachment.spoke)[0].id
  transit_gateway_id      = aws_ec2_transit_gateway.hub.id
  tags                    = { Name = "lz-sdwan-connect" }
}

resource "aws_ec2_transit_gateway_connect_peer" "sdwan" {
  transit_gateway_attachment_id = aws_ec2_transit_gateway_connect.sdwan.id
  peer_address                  = aws_instance.sdwan[0].private_ip
  inside_cidr_blocks            = [var.sdwan_peer_inside_cidr]
  bgp_asn                       = var.customer_asn
}''')
        parts.append('''
output "transit_gateway_id" { value = aws_ec2_transit_gateway.hub.id }
output "dx_gateway_id"      { value = aws_dx_gateway.this.id }''')
    else:
        # Cloud WAN variant (lighter scaffold + notes)
        parts.append('''
# ----------------------------- AWS Cloud WAN -----------------------------
resource "aws_networkmanager_global_network" "this" {
  description = "Landing zone global network"
}

resource "aws_networkmanager_core_network" "this" {
  global_network_id = aws_networkmanager_global_network.this.id
  description       = "Landing zone core network"
}

# Manage segments / attachment policies via a core network policy document
# (aws_networkmanager_core_network_policy_attachment). Spokes attach via
# aws_networkmanager_vpc_attachment; on-prem connects via a DX gateway
# association to the core network.
resource "aws_dx_gateway" "this" {
  name            = "lz-dx-gateway"
  amazon_side_asn = var.amazon_side_asn
}

# resource "aws_networkmanager_dx_gateway_attachment" "onprem" {
#   core_network_id            = aws_networkmanager_core_network.this.id
#   direct_connect_gateway_arn = aws_dx_gateway.this.arn   # associate transit VIF out-of-band
# }
'''
        + ('''
# SD-WAN: connect appliances to Cloud WAN via a Connect attachment (GRE/BGP) on a
# VPC attachment, analogous to the TGW Connect pattern.
''' if sdwan else '')
        + '''output "core_network_id" { value = aws_networkmanager_core_network.this.id }
output "dx_gateway_id"   { value = aws_dx_gateway.this.id }''')

    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# VPC/subnet IaC from a CIDR plan — wired into the connectivity hub
# ---------------------------------------------------------------------------

def _san(s: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", str(s)).strip("_") or "x"


def vpc_network_bundle(plan_rows: list, region: str = "us-east-1") -> bytes:
    """Generate deployable VPC/subnet Terraform from a CIDR allocation plan, plus a
    `locals.spoke_vpc_attachments` map that plugs straight into the connectivity
    module's `var.spoke_vpc_attachments`. CIDRs come from the planner, so the IP
    plan and the connectivity IaC stay consistent (and overlap-free)."""
    by_vpc = {}
    for r in plan_rows:
        by_vpc.setdefault((r["VPC"], r["VPC CIDR"]), []).append(r)

    vpc_tf = ["# vpcs.tf — VPCs & subnets generated from the CIDR planner (overlap-free).",
              "# Deploy from the account that owns these VPCs.\n",
              'provider "aws" { region = var.region }\n']
    locals_tf = ["# spoke_attachments.tf — wire the planned VPCs into the connectivity hub:",
                 "#   module \"connectivity\" {",
                 "#     source                = \"./connectivity\"   # the generated connectivity.tf",
                 "#     spoke_vpc_attachments = local.spoke_vpc_attachments",
                 "#   }",
                 "locals {",
                 "  spoke_vpc_attachments = {"]

    def az_letter(az):
        return chr(ord("a") + int(az) - 1)

    for (vpc, vcidr), subs in by_vpc.items():
        vsan = _san(vpc)
        vpc_tf.append(f'resource "aws_vpc" "{vsan}" {{\n'
                      f'  cidr_block = "{vcidr}"\n'
                      f'  tags = {{ Name = "{vpc}" }}\n}}\n')
        per_az = {}
        for r in subs:
            ssan = f"{vsan}_{_san(r['Subnet'])}"
            vpc_tf.append(
                f'resource "aws_subnet" "{ssan}" {{\n'
                f'  vpc_id            = aws_vpc.{vsan}.id\n'
                f'  cidr_block        = "{r["Subnet CIDR"]}"\n'
                f'  availability_zone = "${{var.region}}{az_letter(r.get("AZ", 1))}"\n'
                f'  tags = {{ Name = "{vpc}-{r["Subnet"]}", Tier = "{r.get("Tier", "")}" }}\n}}\n')
            per_az.setdefault(r.get("AZ", 1), ssan)  # one subnet per AZ for the TGW attachment
        refs = ", ".join(f"aws_subnet.{s}.id" for s in per_az.values())
        locals_tf.append(f'    "{vpc}" = {{ vpc_id = aws_vpc.{vsan}.id, subnet_ids = [{refs}] }}')

    locals_tf += ["  }", "}"]
    variables_tf = (f'variable "region" {{\n  type    = string\n  default = "{region}"\n}}\n')

    readme = f"""# VPC network from the CIDR plan

Generated by AWS Landing Zone Studio. {len(by_vpc)} VPC(s), {len(plan_rows)} subnet(s),
region `{region}`. CIDRs come straight from the **CIDR planner**, so they are
overlap-free and consistent with your IP plan.

## Files
- `vpcs.tf` — `aws_vpc` + `aws_subnet` resources (one subnet per tier × AZ).
- `spoke_attachments.tf` — a `locals.spoke_vpc_attachments` map (one subnet per AZ
  per VPC) shaped to feed the connectivity module's `var.spoke_vpc_attachments`.
- `variables.tf` — region.

## Wire to the connectivity hub
1. Deploy / keep `connectivity.tf` (from the Playbooks tab) — it creates the
   Transit Gateway / Cloud WAN hub and the Direct Connect + SD-WAN paths.
2. Pass the planned VPCs into it:
   ```hcl
   module "connectivity" {{
     source                = "./connectivity"
     spoke_vpc_attachments = local.spoke_vpc_attachments
   }}
   ```
   The TGW VPC attachments then reference exactly these planned VPCs/subnets.

Review before applying; adjust AZ letters/tags as needed for your region.
"""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.md", readme)
        z.writestr("vpcs.tf", "\n".join(vpc_tf))
        z.writestr("spoke_attachments.tf", "\n".join(locals_tf) + "\n")
        z.writestr("variables.tf", variables_tf)
    return buf.getvalue()
