"""Infrastructure-as-Code exporters — turn an LZDesign into deployable artifacts.

Three formats:
  * Terraform (AWS Organizations + OUs + accounts + SCPs)
  * Landing Zone Accelerator (LZA) organization-config.yaml
  * Control Tower setup checklist + Account Factory inputs (Markdown)

Generation is deterministic (no LLM) so output is reviewable and stable.
"""

import json

from lz_core import LZDesign

# ---------------------------------------------------------------------------
# Real SCP policy documents for the core guardrails
# ---------------------------------------------------------------------------

_SCP_DOCS = {
    "deny_leave_org": {
        "Version": "2012-10-17",
        "Statement": [{"Sid": "DenyLeaveOrg", "Effect": "Deny",
                       "Action": "organizations:LeaveOrganization", "Resource": "*"}],
    },
    "deny_root_user": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyRootUser", "Effect": "Deny", "Action": "*", "Resource": "*",
            "Condition": {"StringLike": {"aws:PrincipalArn": "arn:aws:iam::*:root"}},
        }],
    },
    "region_restriction": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyOutsideApprovedRegions", "Effect": "Deny",
            "NotAction": [
                "iam:*", "organizations:*", "route53:*", "cloudfront:*",
                "waf:*", "wafv2:*", "support:*", "budgets:*", "sts:*",
            ],
            "Resource": "*",
            "Condition": {"StringNotEquals": {"aws:RequestedRegion": "__REGIONS__"}},
        }],
    },
    "protect_security_services": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenySecurityTampering", "Effect": "Deny",
            "Action": [
                "cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:UpdateTrail",
                "config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder",
                "config:DeleteDeliveryChannel",
                "guardduty:DeleteDetector", "guardduty:DisassociateFromMasterAccount",
                "securityhub:DisableSecurityHub",
            ],
            "Resource": "*",
        }],
    },
    "deny_imdsv1": {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "RequireImdsV2", "Effect": "Deny", "Action": "ec2:RunInstances",
            "Resource": "arn:aws:ec2:*:*:instance/*",
            "Condition": {"StringNotEquals": {"ec2:MetadataHttpTokens": "required"}},
        }],
    },
}


def _hcl_jsonencode(doc: dict, regions: list) -> str:
    s = json.dumps(doc, indent=2)
    if "__REGIONS__" in s:
        s = s.replace('"__REGIONS__"', json.dumps(regions))
    return s


# ---------------------------------------------------------------------------
# Terraform
# ---------------------------------------------------------------------------

def terraform_export(d: LZDesign) -> str:
    n_env = [e for e in d.environments]
    workloads = [f"workload-{i + 1}" for i in range(d.num_workloads)]
    per_env = d.account_strategy == "Account per workload per environment"
    per_wl = d.account_strategy in ("Account per workload", "Account per workload per environment")

    out = []
    out.append(f'''# ---------------------------------------------------------------
# AWS Landing Zone — generated by AWS Landing Zone Studio
# Strategy: {d.account_strategy} | Network: {d.network_pattern}
# Review carefully before applying. Account emails MUST be unique.
# ---------------------------------------------------------------

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{ source = "hashicorp/aws", version = ">= 5.40" }}
  }}
}}

provider "aws" {{
  region = "{d.regions[0] if d.regions else 'us-east-1'}"
  # Run from the management account (or a delegated admin for Organizations)
}}

variable "account_email_domain" {{
  description = "Domain used for root emails, e.g. aws+%s@example.com"
  type        = string
}}

locals {{
  environments = {json.dumps(n_env)}
  workloads    = {json.dumps(workloads)}
  approved_regions = {json.dumps(d.regions)}
}}

# ----------------------------- Organization -----------------------------

resource "aws_organizations_organization" "this" {{
  feature_set = "ALL"
  enabled_policy_types = ["SERVICE_CONTROL_POLICY", "TAG_POLICY"]
  aws_service_access_principals = [
    "cloudtrail.amazonaws.com",
    "config.amazonaws.com",
    "guardduty.amazonaws.com",
    "securityhub.amazonaws.com",
    "sso.amazonaws.com",
    "backup.amazonaws.com",
  ]
}}

# ----------------------------- OU structure -----------------------------

resource "aws_organizations_organizational_unit" "security" {{
  name      = "Security"
  parent_id = aws_organizations_organization.this.roots[0].id
}}

resource "aws_organizations_organizational_unit" "infrastructure" {{
  name      = "Infrastructure"
  parent_id = aws_organizations_organization.this.roots[0].id
}}

resource "aws_organizations_organizational_unit" "workloads" {{
  name      = "Workloads"
  parent_id = aws_organizations_organization.this.roots[0].id
}}
''')

    if per_env:
        out.append('''
resource "aws_organizations_organizational_unit" "workloads_prod" {
  name      = "Prod"
  parent_id = aws_organizations_organizational_unit.workloads.id
}

resource "aws_organizations_organizational_unit" "workloads_nonprod" {
  name      = "NonProd"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
''')

    out.append('''
resource "aws_organizations_organizational_unit" "sandbox" {
  name      = "Sandbox"
  parent_id = aws_organizations_organization.this.roots[0].id
}

resource "aws_organizations_organizational_unit" "suspended" {
  name      = "Suspended"
  parent_id = aws_organizations_organization.this.roots[0].id
}

# ----------------------------- Core accounts -----------------------------

resource "aws_organizations_account" "log_archive" {
  name      = "log-archive"
  email     = format(var.account_email_domain, "log-archive")
  parent_id = aws_organizations_organizational_unit.security.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}

resource "aws_organizations_account" "security_tooling" {
  name      = "security-tooling"
  email     = format(var.account_email_domain, "security-tooling")
  parent_id = aws_organizations_organizational_unit.security.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}
''')

    if d.network_pattern != "Flat VPC peering":
        out.append('''
resource "aws_organizations_account" "network" {
  name      = "network"
  email     = format(var.account_email_domain, "network")
  parent_id = aws_organizations_organizational_unit.infrastructure.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}
''')

    out.append('''
resource "aws_organizations_account" "shared_services" {
  name      = "shared-services"
  email     = format(var.account_email_domain, "shared-services")
  parent_id = aws_organizations_organizational_unit.infrastructure.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
  lifecycle { prevent_destroy = true }
}

# ---------------------------- Workload accounts ----------------------------
''')

    if per_env:
        out.append('''
locals {
  workload_accounts = {
    for pair in setproduct(local.workloads, local.environments) :
    "${pair[0]}-${pair[1]}" => {
      workload = pair[0]
      env      = pair[1]
      prod     = pair[1] == "prod"
    }
  }
}

resource "aws_organizations_account" "workload" {
  for_each  = local.workload_accounts
  name      = each.key
  email     = format(var.account_email_domain, each.key)
  parent_id = each.value.prod ? aws_organizations_organizational_unit.workloads_prod.id : aws_organizations_organizational_unit.workloads_nonprod.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
}
''')
    elif per_wl:
        out.append('''
resource "aws_organizations_account" "workload" {
  for_each  = toset(local.workloads)
  name      = each.key
  email     = format(var.account_email_domain, each.key)
  parent_id = aws_organizations_organizational_unit.workloads.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
}
''')
    elif d.account_strategy == "Account per environment":
        out.append('''
resource "aws_organizations_account" "workload" {
  for_each  = toset(local.environments)
  name      = "workloads-${each.key}"
  email     = format(var.account_email_domain, "workloads-${each.key}")
  parent_id = aws_organizations_organizational_unit.workloads.id
  role_name = "OrganizationAccountAccessRole"
  close_on_deletion = false
}
''')

    # SCPs
    out.append("\n# ------------------------- Service Control Policies -------------------------\n")
    scp_targets = {
        "deny_leave_org": "aws_organizations_organization.this.roots[0].id",
        "deny_root_user": "aws_organizations_organizational_unit.workloads.id",
        "region_restriction": "aws_organizations_organization.this.roots[0].id",
        "protect_security_services": "aws_organizations_organization.this.roots[0].id",
        "deny_imdsv1": "aws_organizations_organizational_unit.workloads.id",
    }
    for name, doc in _SCP_DOCS.items():
        out.append(f'''
resource "aws_organizations_policy" "{name}" {{
  name    = "{name.replace('_', '-')}"
  type    = "SERVICE_CONTROL_POLICY"
  content = jsonencode({_hcl_jsonencode(doc, d.regions)})
}}

resource "aws_organizations_policy_attachment" "{name}" {{
  policy_id = aws_organizations_policy.{name}.id
  target_id = {scp_targets[name]}
}}
''')

    out.append('''
# Suspended OU: deny everything
resource "aws_organizations_policy" "suspended_deny_all" {
  name = "suspended-deny-all"
  type = "SERVICE_CONTROL_POLICY"
  content = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Sid = "DenyAll", Effect = "Deny", Action = "*", Resource = "*" }]
  })
}

resource "aws_organizations_policy_attachment" "suspended_deny_all" {
  policy_id = aws_organizations_policy.suspended_deny_all.id
  target_id = aws_organizations_organizational_unit.suspended.id
}
''')
    return "".join(out)


# ---------------------------------------------------------------------------
# Landing Zone Accelerator config
# ---------------------------------------------------------------------------

def lza_config(d: LZDesign) -> str:
    per_env = d.account_strategy == "Account per workload per environment"
    envs = d.environments
    home = d.regions[0] if d.regions else "us-east-1"

    lines = [f"""# organization-config.yaml — Landing Zone Accelerator
# Generated by AWS Landing Zone Studio. Review before deploying with LZA.
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Workloads"""]
    if per_env:
        lines.append("""  - name: Workloads/Prod
  - name: Workloads/NonProd""")
    lines.append("""  - name: Sandbox
  - name: Suspended

serviceControlPolicies:
  - name: deny-leave-org
    description: Prevent accounts from leaving the organization
    policy: scp-deny-leave-org.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Root]
  - name: region-restriction
    description: Deny activity outside approved regions
    policy: scp-region-restriction.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Root]
  - name: protect-security-services
    description: Deny tampering with CloudTrail / Config / GuardDuty / Security Hub
    policy: scp-protect-security.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Root]
  - name: suspended-deny-all
    description: Quarantine policy
    policy: scp-deny-all.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: [Suspended]

taggingPolicies: []
backupPolicies: []""")

    lines.append(f"""

# accounts-config.yaml (fragment)
mandatoryAccounts:
  - name: Management
    description: Organization management account
    email: aws+management@example.com   # CHANGE ME
    organizationalUnit: Root
  - name: LogArchive
    description: Immutable centralized logs
    email: aws+log-archive@example.com  # CHANGE ME
    organizationalUnit: Security
  - name: Audit
    description: Security tooling / delegated admin
    email: aws+audit@example.com        # CHANGE ME
    organizationalUnit: Security

workloadAccounts:""")
    if per_env:
        for i in range(min(d.num_workloads, 50)):
            for e in envs:
                ou = "Workloads/Prod" if e == "prod" else "Workloads/NonProd"
                lines.append(f"""  - name: workload-{i + 1}-{e}
    email: aws+workload-{i + 1}-{e}@example.com  # CHANGE ME
    organizationalUnit: {ou}""")
    else:
        for i in range(min(d.num_workloads, 50)):
            lines.append(f"""  - name: workload-{i + 1}
    email: aws+workload-{i + 1}@example.com  # CHANGE ME
    organizationalUnit: Workloads""")

    lines.append(f"""

# global-config.yaml (fragment)
homeRegion: {home}
enabledRegions: {json.dumps(d.regions)}
managementAccountAccessRole: OrganizationAccountAccessRole
cloudwatchLogRetentionInDays: 365
centralizedLoggingBucket:
  lifecycleRules:
    - enabled: true
      expiration: 730
""")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Control Tower checklist
# ---------------------------------------------------------------------------

def control_tower_checklist(d: LZDesign) -> str:
    per_env = d.account_strategy == "Account per workload per environment"
    home = d.regions[0] if d.regions else "us-east-1"
    md = [f"""# Control Tower Setup — {d.org_size} profile

## 1. Prerequisites
- [ ] Management account with billing + root access secured (MFA, no access keys)
- [ ] Two fresh email addresses for **Log Archive** and **Audit** accounts
- [ ] Home region: **{home}** (governed regions: {', '.join(d.regions)})

## 2. Launch Control Tower
- [ ] Console -> Control Tower -> Set up landing zone
- [ ] Foundational OU: `Security` (Log Archive + Audit created automatically)
- [ ] Additional OU: `Workloads`{' with `Prod` / `NonProd` children' if per_env else ''}
- [ ] Enable AWS CloudTrail org trail (mandatory control)
- [ ] KMS encryption for Control Tower resources: **enabled**

## 3. Post-launch configuration
- [ ] Create OUs: `Infrastructure`, `Sandbox`, `Suspended` (register each with CT)
- [ ] Enable IAM Identity Center; connect {"external IdP (" + d.identity_model + ")" if d.identity_model.startswith("External") else "Identity Center directory"}
- [ ] Delegate GuardDuty + Security Hub + Config admin to the **Audit** account
- [ ] Apply elective/proactive controls per compliance: {', '.join(d.compliance) or 'baseline only'}

## 4. Account Factory
Provision accounts with these inputs:

| Account | OU | Purpose |
|---|---|---|
| network | Infrastructure | {d.network_pattern} hub |
| shared-services | Infrastructure | CI/CD, AMIs, registries |"""]
    if per_env:
        md.append("".join(
            f"\n| workload-{i + 1}-{e} | Workloads/{'Prod' if e == 'prod' else 'NonProd'} | Workload account |"
            for i in range(min(d.num_workloads, 20)) for e in d.environments))
    else:
        md.append("".join(
            f"\n| workload-{i + 1} | Workloads | Workload account |"
            for i in range(min(d.num_workloads, 20))))

    md.append(f"""

## 5. Network ({d.network_pattern})
- [ ] Provision Transit Gateway / core network in the **network** account
- [ ] Share via AWS RAM with the Workloads OU
- [ ] {"Centralize egress (NAT + inspection) in the network account" if "egress" in d.network_pattern.lower() else "Plan egress per the chosen pattern"}

## 6. Operations
- [ ] Account Factory Customization (AFT) or Customizations for Control Tower (CfCT) for baselines-as-code
- [ ] Budgets + budget actions on Sandbox OU
- [ ] {"AWS Backup org policies with cross-region copies" if d.backup_dr else "Define backup strategy per workload"}
""")
    return "".join(md)
